### ISSUE TITLE
Scripts Error

### ISSUE THREAD

**Issue by gledson999** [uzuhenry/Dw1-Script-Decoder#1]
Hello, I'm trying the PAL version, but these error texts appear here:
![image](https://github.com/user-attachments/assets/8bed1aef-56b8-49f0-8498-20c8ca1df3ce)

Furthermore, these texts that have errors, in the case of script 102 for example, some unknown functions appear as shown in the image below.
![image](https://github.com/user-attachments/assets/5b482fd2-3a32-48c0-9584-c41e6c21e35f)

Do you plan to fix this scripts errors?

My other question is: Do you plan to make the tool compatible with the NTSC version?

**Comment by uzuhenry** [comment]
The first message is a warning rather than an error, it's warning you that those scripts would be too big to correctly load on the japanese or patched version. USA and EU scripts have a bigger memory allocation for scripts so the vanilla scripts for those regions have scripts that go beyond the memory limit of the patched version. Not really an error, just a warning.

As for the second one, while i agree that the wording used there can be improved, it's meant to say that it unkown function 6B, it's a not completely understood function that it's used for championship configuration. You can leave that script as is.

As for the final question, i did never get to figure out how the usa header worked differently than the japanese and european header. So, maybe in the future i'll find a way to fix it and support both script headers.

**Comment by gledson999** [comment]
I understood, the American NTSC version would be ideal for your tool to have full compatibility, many people use this version in various mods, thanks.
